version: "3.8"
services:
  tomcat:
    image: tomcat:8.5-jre8
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: pwd/logs
        target: /usr/local/tomcat/logs
    command: chmod -R +r /usr/local/tomcat/logs
    
